apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-bookstore-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gin-bookstore-app
  template:
    metadata:
      labels:
        name: gin-bookstore-app
    spec:
      containers:
      - name: gin-bookstore-app
        image: kgurudut/gin-bookstore:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8085
            name: http
            protocol: TCP