apiVersion: v1
kind: Service
metadata:
  name: gin-bookstore-service
  namespace: app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: gin-bookstore-app